to.pdf(figure1(), "output/Fig1.pdf", width=8, height=4, verbose=FALSE)
to.pdf(figure2(), "output/Fig2.pdf", width=4, height=4, verbose=FALSE)
to.pdf(figure3(), "output/Fig3.pdf", width=8, height=4, verbose=FALSE)
to.pdf(figure4(), "output/Fig4.pdf", width=8, height=4, verbose=FALSE)
to.pdf(figure5(acifits, tumspot), "output/Fig5.pdf", width=8, height=8, verbose=FALSE)
