to.pdf(figure1(), "output/figure1.pdf", width=8, height=4, verbose=FALSE)
to.pdf(figure2(), "output/figure2.pdf", width=4, height=4, verbose=FALSE)
to.pdf(figure3(), "output/figure3.pdf", width=8, height=4, verbose=FALSE)
to.pdf(figure4(), "output/figure4.pdf", width=8, height=4, verbose=FALSE)
to.pdf(figure5(), "output/figure5.pdf", width=8, height=8, verbose=FALSE)
